# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui',
# licensing of 'info.ui' applies.
#
# Created: Sat Mar 14 21:57:37 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import menu

class Ui_Artefactinf(object):
    def closeWindow(self, Artefactinf):
        Artefactinf.hide()
    def openmenu(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = menu.Ui_MenuWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Artefactinf):
        Artefactinf.setObjectName("Artefactinf")
        Artefactinf.resize(585, 541)
        self.centralwidget = QtWidgets.QWidget(Artefactinf)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openmenu)
        self.pushButton.clicked.connect(lambda: self.closeWindow(Artefactinf))
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.openmenu)
        self.pushButton_2.clicked.connect(lambda: self.closeWindow(Artefactinf))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        Artefactinf.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Artefactinf)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        Artefactinf.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Artefactinf)
        self.statusbar.setObjectName("statusbar")
        Artefactinf.setStatusBar(self.statusbar)

        self.retranslateUi(Artefactinf)
        QtCore.QMetaObject.connectSlotsByName(Artefactinf)

    def retranslateUi(self, Artefactinf):
        Artefactinf.setWindowTitle(QtWidgets.QApplication.translate("Artefactinf", "Информация об артефактах", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Artefactinf", "Название артефакта:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Artefactinf", "ID:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Artefactinf", "Тип артефакта:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Artefactinf", "Цвет:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Artefactinf", "Примеси:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Artefactinf", "Водопоглащение:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Artefactinf", "Текстура:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Artefactinf", "Толщина стенки:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Artefactinf", "Следы брака:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Artefactinf", "Местоположение:", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Artefactinf", "Сохранить и печать", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Artefactinf", "Назад", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Artefactinf = QtWidgets.QMainWindow()
    ui = Ui_Artefactinf()
    ui.setupUi(Artefactinf)
    Artefactinf.show()
    sys.exit(app.exec_())

